### ISSUE TITLE
[Casino/Feature Request] Adjustable game timeout

### ISSUE THREAD

**Issue by TrustyJAID** [Redjumpman/Jumper-Cogs#101]
# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Casino
Version: 2.0.0

# Feature Description
Add a way to adjust the timeout for games being played. I have met some users who have a disability preventing them from playing blackjack and other games because the game times out waiting for their play. Simply add a setting and command to adjust the timeout for commands without having to manually modify it. Note: This is separate from the cooldown where players spam the chat.

**Comment by Redjumpman** [comment]
I don't know if I want to have a command to change the timeout. I'll have to think about it. For now, I'll consider increasing the time a little bit. What disability do your users have which requires them to need more than 15 seconds? I am happy to help, but I need some more information.

**Comment by TrustyJAID** [comment]
I manually adjusted it to 30 seconds and that seemed okay. I don't know the full extent of his disability but it would be better to make it a variable we can adjust where most people might not use it but those that do need it can without having to modify the code every time there is an update.

**Comment by Redjumpman** [comment]
I am looking into a good way to do this. I think maybe just increasing the time in general might be the fastest solution. The problem with letting you set a variable, is that it will now have to do an additional pull from the data, just to get a timeout. That's a lot of extra calls, for something that isn't always met. Ultimately, I don't want anyone to feel excluded. I just need to make sure I do this right, so that it isn't a huge performance hit.

**Comment by Redjumpman** [comment]
Added increased timeouts as of Casino 2.0.4
