### ISSUE TITLE
The heist cog makes Red restart every 3 minutes or so.

### ISSUE THREAD

**Issue by nikolaaa4** [Redjumpman/Jumper-Cogs#12]
There is no error log, the uptime command does not log the restart, but the bot goes offline/online several times.

**Comment by Redjumpman** [comment]
How many servers / users do you have using the bot? Does the problem occur if you unload heist? What are the specs for the machine running the bot? Do you have the latest update for heist? Did this problem occur once you installed my cog or did it start happening after some time? I need the answers to these questions before I am able to continue diagnose the problem further. Thank you for reporting and I do apologize for any inconvenience this may have caused.

**Comment by nikolaaa4** [comment]
The bot is running on 510 servers, no it doesn't occur once i unload it, 2gb ram with 5 cores, yes i did, it started happening after some time.

**Comment by Redjumpman** [comment]
I have some optimizations that need to happen once I return from vacation. The problem is all the requests to write and all the awaits that I thrown in haphazardly. The code is reaaaaally bad. But that will (hopefully) solve your issues in the short term. In the long term as you grow to more servers it will become a problem again because of the writes. Already discussing plans to improve red's core file IO with tekulvw to improve that portion. I return on the 17th of November and will be doing work on it as soon as I can. I will leave this PR open until resolved. Send me a msg on discord so I can later send you improvements to the code. Thank you.

**Comment by Redjumpman** [comment]
Update to heist 2.0 . If you encounter a nnew bug, post a seperate issue.
