### ISSUE TITLE
Race Emoji Error

### ISSUE THREAD

**Issue by ghost** [Redjumpman/Jumper-Cogs#171]
When running my own race set with my own emoji it just shows the statement for that emoji not the emoji how to fix this For example. :elixir: instead of the emoji while it works perfectly well with the orignal race setting but just as i load my own race set it shows this.

![Screenshot_20190506-192018_Discord](https://user-images.githubusercontent.com/44896455/57228891-754a7380-7032-11e9-96ac-ef766de4b04b.jpg)

**Comment by Flame442** [comment]
Did you edit the code in order to add custom emojis? discord.py (the library that Red runs on) treats custom emojis very different to unicode emojis, so if you edited the code you would need to account for that. It would also not be considered a bug with the cog since you edited the code before it broke.
