### ISSUE TITLE
[Shop] Administrator permission issue

### ISSUE THREAD

**Issue by Zenchaeus** [Redjumpman/Jumper-Cogs#249]
So my friend who is an Admin tried using the "shop pending" command to clear a member's pending request. But he can't see all the commands of the cog. I tried giving him a role that has the Administrator role permission turned on from the server settings and it works. The thing is, I don't want to give that special Administrator permission to any role except for me so I can prevent them from messing with stuff. Is there any way to fix this?

**Comment by aikaterna** [comment]
The check for a local shop involves checking for a Red Admin role, whether the invoker is the guild owner, or whether they have the Administrator permission on the server. The Red Admin role part of the check was broken as it was expecting one role (old Red behaviour) vs a list of roles (a newer implementation of Red's Admin roles). This check is fixed in the commit referenced above, so you don't have to give your friend the Administrator perms on the server for this now, but they do have to have a role that's set as one of Red's Admin roles. Since you mentioned your friend is an "Admin" I'm assuming they already have one of these Red Admin roles on your bot and it just wasn't working properly until this fix. Update your cog and give this a try and see how it goes for you.
