### ISSUE TITLE
lottery issue and probably a suggestion

### ISSUE THREAD

**Issue by skeith** [Redjumpman/Jumper-Cogs#33]
I believe I have the latest version of lottery

Issue : Lottery will try to give a winner their prize even though they have no bank account.
![image](https://cloud.githubusercontent.com/assets/340284/23247523/95bd1170-f9d5-11e6-8164-feb588939706.png)

Suggestion : Can we escape / prevent using `@` on role argument for lottery? Because it result in double `@@` when we use `@everyone`
![image](https://cloud.githubusercontent.com/assets/340284/23247535/b3fe7fc0-f9d5-11e6-81f7-39702cf5ff32.png)

**Comment by Redjumpman** [comment]
The first one is a complex issue I'll look at trying to fix. One thing that comes to mind is just skipping over someone who entered the lottery and didn't have an account with economy. Basically if the winner does not have an account, then it will draw another winner. Seems only fair if your giving out a cash prize and they are too stupid to register for an account. I have no intentions of registering for them. 

As for the second suggestion. The reason I have it do an @everyone is because I needed a way to notify everyone on the server that a lottery for g-pop (general population) was being held. If someone on the server is getting annoyed by the server owner using @everyone to ping people about a giveaway they need to make use of this:
![image](https://cloud.githubusercontent.com/assets/18455011/23247661/f0820310-f960-11e6-85b5-8cf54ac091a9.png)

**Comment by skeith** [comment]
@Redjumpman 
for the 2nd suggestion, I actually tried `setlottery role everyone` and it fail, because the role name is actually `@everyone` but because oh this code
```python
                else:
                    lottery_role = "@" + settings["Config"]["Signup Role"]
                settings["Config"]["Lottery Member Requirement"] = True```
it prints double `@`

**Comment by Redjumpman** [comment]
I see what you mean. I'll look into fixing that.

**Comment by Core002** [comment]
For the first issue, couldn't you prevent them from even using !lottery play at all and give an error of you need an account before attempting to play the lottery.
`except NoAccount:
            await self.bot.say("{} You need an account to use the slot "
                               "machine. Type `{}bank register` to open one."
                               "".format(author.mention, ctx.prefix))`

Like so from economy.py ^

And attach it to the _play_lottery 
`@lottery.command(name="play", pass_context=True)
    async def _play_lottery(self, ctx):
        """Enters a user into an on-going lottery."""
        server = ctx.message.server
        user = ctx.message.author
        settings = self.check_server_settings(server)
        if not settings["Config"]["Lottery Active"]:
            await self.bot.say("There is no on-going lottery.")
        elif await self.requirement_check(ctx, settings):
            if user.id not in settings["Lottery Players"]:
                settings["Lottery Players"][user.id] = {"Name": user.name, "Mention": user.mention}
                players = len(settings["Lottery Players"].keys())
                dataIO.save_json(self.file_path, self.system)
                self.update_play_stats(settings, user.id)
                await self.bot.say("{} you have been added to the lottery. "
                                   "Good luck!\nThere are now {} user(s) participating in "
                                   "the lottery".format(user.mention, players))
            else:
                await self.bot.say("You have already entered into the lottery.")`

**Comment by Redjumpman** [comment]
With the newest lottery update it will catch people who are trying to enter a lottery without a bank account when a credit prize is set.
