### ISSUE TITLE
Store issues

### ISSUE THREAD

**Issue by RSNFreud** [Redjumpman/Jumper-Cogs#42]
1. How does the process if buying work. Buy an item then what? 
2. Pending.. Can the id be numbers? Easier to type on mobile 
3. Setrole doesn't work for notifications
4. What status options are there in pending 
5. Redeem didn't seem to do anything 
6. Inventory isn't working

**Comment by Redjumpman** [comment]
1. You buy an item, and then you can redeem it, based on some "value" you gave it in your server. For example, maybe the item will grant them a free character name change in a game you made. Or a steam code. Something like that. 

2. The pending can be searched by the userid or the code. The code is uniquely generated. 

3. Setrole works for me! You have to set a shop role, that corresponds to a role on your server. For example, if you have an admin role on your server, you can set it up as such:

![image](https://cloud.githubusercontent.com/assets/18455011/24304261/bbd74336-1086-11e7-85c4-d2789f537b3d.png)

4. You can change the status to any 10 character word. Pending, Review, In-Transit, etc.  This is to let the user know, what actions you are taking since the item was redeemed.

5. Redeem adds the item to the redeem list. It is your job as the admin to figure out what you want to do with the items. 

6. How is inventory not working? If you have an item, and you type >inventory it should bring up your inventory. If you do not, then it won't display anything because you have nothing.

7. Buy msgs are for a different buy mode. It skips the redeem process, and sends the user a msg when they redeem the item. For example, you have steam games in your shop, you can add a key to each game, and they are sent the key when they redeem the item. BE CAREFUL OF THIS MODE. I am not responsible for any loss of items.
