### ISSUE TITLE
Feature Request - Heist - List Heist Participants

### ISSUE THREAD

**Issue by xSoonkyu** [Redjumpman/Jumper-Cogs#47]
Hi Redjumpman,

Our Discord server has been using your "Jumper-Cogs Heist" functionality for a while now, and has really been enjoying the game! A feature that I was hoping to request was the option to add an additional bot message to list all the participants for a single instance of a heist, probably placed during the Heist Start message. 

If implemented, this would most likely be an toggleable feature, as thinking of server instances where the userbase is very large, this extra text line might be quite distracting.

Thanks for your time! :)

**Comment by Redjumpman** [comment]
Were you thinking of having a command like >heist crew that shows all the names of people that are currently in the crew? or adding on the the message that says "You now have X players in the crew."

**Comment by xSoonkyu** [comment]
I think adding the message instead of a separate command request would be easier. I was thinking of placing it right before the heist starts.

So a quick draft up:

A: !join
Bot: A has joined the crew. The crew now has 1 members.
B: !join
Bot: B has joined the crew. The crew now has 2 members.
C: !join
Bot: C has joined the crew. The crew now has 3 members.
Bot: Get ready! The heist is starting with members **"A, B, and C"**
Bot: The crew has decided to hit **XYZ Bank.**

**Comment by Redjumpman** [comment]
Funny thing about that, is that heist did that when I was first developing it. The problem is, as you mentioned earlier, when there is a large server. It's difficult and somewhat spammy to print a wall of text for 20+ players. I think that the best solution would be to truncate the members after a certain number. So a sample would be:

"Get ready! The heist is starting with "A, B, C, and 17 other members." Something like that. Maybe the person who started the heist + two people? I don't hate the idea, I just need to figure out the best way to implement it. But I will add a command later to show who all is in the crew maybe a >heist crew command.

Based on this conclusion I'll add the planned label.

**Comment by xSoonkyu** [comment]
Awesome to hear! :)
That sounds great, and perhaps to cater to different server sizes, an parameter in "settings["Config"]" to either be configured to: None (current build), Short (few names), or Full (all names)?

**Comment by Redjumpman** [comment]
I think that's a good solution. I'll probably set the default to short. When I finish up with my other items on the road map, I'll swing back around to this request.

**Comment by Redjumpman** [comment]
Feature added in patch 2.2.14 in commit 8c219f2
