### ISSUE TITLE
Shop List Command HTTP Error

### ISSUE THREAD

**Issue by Unieveth** [Redjumpman/Jumper-Cogs#75]
When I try to do ?shop list and it asks for a page number and I enter 1 it gives this error https://gist.github.com/Unieveth/6efedcbaaa16eb7cd11a016e83a67f96.  But when I do the same command, but instead of 1 I do 2 it has no errors.
System Info:
https://gist.github.com/Unieveth/58d25ea55f0faea63c27eb96a364d838.  Also Running Ubuntu Linux

**Comment by Redjumpman** [comment]
That's probably because you either
 
A.) have prices like 90198040101100393 really large prices, 
B.) You have really long item names through out the first list, 
C.) Both of those things. 

The reason this occurs is because there is more than 2000 characters in the message that it is trying to send. Discord can only send messages at or below this number. I tried, to curb this problem by dividing it up into pages of (I think) 15 items max per page. If you trim down the names, prices, or both in your item list it will resolve the error. Please report back your findings and let me know if this helps to fix your issue.

An additional note, the shop rewrite for Red V3 has better handling for these situations, but will not be added into v2.

**Comment by Redjumpman** [comment]
This has been found to be an issue with your item list. Closing the issue.
