### ISSUE TITLE
[Casino/Feature Request] - Increase payout for certain memberships in casino

### ISSUE THREAD

**Issue by jjay12365** [Redjumpman/Jumper-Cogs#97]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [x] feature request

# **Cog Information**

Name:  Casino

# Feature Description
Allow an option in memberships to have an additional payout multiplier. So a person with a membership can earn more. Example: a person is in a membership that adds an additional 25% payout so the payout will be (bet * game's multiplier * memberships multiplier)

**Comment by Redjumpman** [comment]
Hey this is a good idea. The request came at a good time since I've been working on the new membership system in V3. Since I'm removing chips (because the new economy rocks) the perks felt a little lackluster. This will definitely breath some life into the system. I'm adding it to the Casino road map and approving this request. Thanks for the post.

**Comment by jjay12365** [comment]
I already have it working on the current version of casino. Not sure if you can get any use from that.

**Comment by Redjumpman** [comment]
I don't think it will be translatable since the majority of Casino was rewritten for V3. I appreciate the offer, and normally I would suggest doing a PR for your feature; however, I'm taking a hard line on bug fix PRs only for V2.

**Comment by Redjumpman** [comment]
Added in Casino 2.0.0 for V3.
